### ISSUE TITLE
Nift is not managing a project

### ISSUE THREAD

**Issue by cup** [nifty-site-manager/nsm#14]
Starting here:

https://nifty-site-manager.com/resources/get_started

I do:

~~~
$ nsm clone https://github.com/nifty-site-manager/simple-site.git
$ nsm build-updated
Nift is not managing a project from C:\ (or any accessible parent directories)

$ cd simple-site
$ nsm build-updated
Nift is not managing a project from C:\simple-site (or any accessible parent
directories)
~~~

it seems the instructions are missing something

**Comment by n-ham** [comment]
I'm not sure what happened with that repository, there's no .siteinfo/.nsm directory which nsm/nift uses when managing websites. 

The first paragraph would have been the same anyway as you had not cd'd in to the simple-site directory, but the second one is failing because there's no config directory in the repo. 

I've deleted the nifty-site-manager/simple-site repo now to avoid other people getting confused in the future. Try any of the templates at https://www.nift.cc/resources/templates.html and you should have more luck. Please yell if you run in to any more problems.

**Comment by cup** [comment]
Looks good, thanks

~~~
$ nsm clone https://github.com/nsm-templates/simple-site.git
$ cd simple-site
$ nsm build-updated
all 2 output files are already up to date
time taken: 0 seconds
~~~
