### ISSUE TITLE
Comment syntax

### ISSUE THREAD

**Issue by ghost** [nifty-site-manager/nsm#18]
Originally started here: https://github.com/nifty-site-manager/nsm/issues/13#issuecomment-573371572

**Comment by n-ham** [comment]
I still haven't thought of anything I really like with the comments. Thoughts on eg. `@//(comment)`?

**Comment by cup** [comment]
> Would you use `@/* comment @*/-` and `<@-- comment --@>-` or is that too
> gross?

those are both ok. the first is less characters, but I think the second is more
readable, so its a judgement call. Again, Hugo uses:

~~~
{{/* comment */}}
~~~

so either one would be same or less characters.

> One option with comments is to have an actual function that can take options
> and parameters. Considering things like `@//(comment)`, `@/*(comment)` or
> `@%(comment)`.

Now this I like. Seems like a good and easy way to fix the problem.

> Then I can have options like `!p` to not parse the comment text, and `!tws`
> for no trailing whitespace (open to suggestions for `!tws`). Eg.
> `@//{!tws}(comment)`.

That looks fine as well, similar to Go `interface` syntax. I dont have a
suggestion for `!tws`.

> Thoughts? And any preferences on what the function name should be?

Function name? If only one choice, I would say `@//(comment)`. Another option
would be to have the name as `@comment(sunday)` or `@comm(sunday)`, with an
alias of `@//(sunday)`, so people can do what works for them. I am torn on that
though because Ruby and PHP have some aliases, and I think it can create
confusion sometimes.

**Comment by n-ham** [comment]
I will have a think and see what I can decide on. I have `@# comment` hard-coded to be usable at the end of lines where input parameters are, eg. you might have:

    @link(url, @# comment
              txt)

So I am trying to avoid getting rid of the `@# comment` syntax, and it's kind of nice having the `@// comment` syntax for single-line **parsed** comments. So I'm not sure what to have the shorthand syntax for `@comm(txt)` to be. I'm not sure if I like `!tws` as option for no-trailing-whitespace either. 

It might be worth me adding some options like `php` and `md` to `@link` so people can do links for other kinds of output files as well. I could probably even check the output extension and do the link based on that, defaulting to the html case. For example you can use Nift to generate php files, css files, js files, md files, etc. etc.. You could even conceivably use it for non-website projects.

**Comment by n-ham** [comment]
I think I prefer `->` as the option to skip trailing whitespace rather than `!tws`.

**Comment by n-ham** [comment]
I have added `@->` syntax to skip to the next non-whitespace at any point in any file. 

I am just a little unsure about whether I'd ever want to have an `@->(params)` function for dereferencing pointers. I don't think I will though, since the function names are parsed you can basically just use a string as a pointer. If you have a pointer `ptr` that's basically just a string you can call a function of an object it points to for example with `@"@[ptr].funcName"()` or a variable of an object it points to can be printed for example with `@[@[ptr].varName]`, and I don't think you could really do anything nice there with `@->(params)` anyway. 

I don't think I can make the multi-line comments for skipping whitespace after align that nicely with it either though, it almost works but isn't that nice. Options include things like:

`@--- comment @--->`

`<@-- comment --@->`

`@/* comment @*/->` or `@/* comment @*/>`

Would you consider that acceptable at all?

**Comment by n-ham** [comment]
I think I have an acceptable solution. I think more often than not you will want to skip the trailing whitespace. So when one doesn't want the trailing whitespace skipped they can use:

```
@/*
	this is gross
@*/!

@---
	this isn't that nice
@---!

<@--
	gross
--@>!
```

**Comment by n-ham** [comment]
This should now all be fixed and hopefully finalised, see [here](https://www.nift.cc/docs/fns/comments.html)
